### ISSUE TITLE
Lista y selección de la moneda tiene un comportamiento extraño

### ISSUE THREAD

**Issue by glabrat** [gpincheiraa/bln-frontend-project1#14]
**Describe the bug**
Cada 1 minuto se refresca la data y por así decirlo borra la información que tenía anteriormente

La lista se vuelve cada vez más larga, se le agregan muchos items
Al seleccionar una moneda se ilumina una parte de la tabla, pero al cabo de 1 minuto se elimina esa selección

**Comment by gpincheiraa** [comment]
Para la siguiente Issue, favor seguir el template por defecto para los "bug report"
