### ISSUE TITLE
La URL de la build en Travis CI no concuerda

### ISSUE THREAD

**Issue by glabrat** [gpincheiraa/bln-frontend-project1#26]
La URL o el link que se ve al pasar el mouse sobre la imagen de la build, aparece otro proyecto

https://travis-ci.org/gpincheiraa/proyecto_1

![imagen](https://user-images.githubusercontent.com/19995834/41213387-11e4a8d8-6d13-11e8-9d62-382e7eec57fc.png)

Cambiar la URL de: 
https://travis-ci.org/gpincheiraa/proyecto_1

a

https://travis-ci.org/gpincheiraa/bln-frontend-project1

**Comment by gpincheiraa** [comment]
Favor asociar esta issue al project release1 para así verlo en el tab “projects”.

**Comment by glabrat** [comment]
Listo
