### ISSUE TITLE
Probar Ejercicio 1

### ISSUE THREAD

**Issue by gpincheiraa** [gpincheiraa/bln-frontend-project1#35]
**Descripción:**
En el ejercicio 1 se tiene como objetivo el uso de `templates strings` (o sumas de strings), utilizar `querySelector` e `innerHTML` para crear las columnas de la tabla.
También se pide crear toda la estructura HTML de una tabla
El objetivo de esta tarea es corroborar si la redacción y las instrucciones están correctas.

**Resultado esperado**
-Seguir instrucciones de ejercicio 1 partiendo desde un proyecto forkeado.
- Corroborar si las instrucciones en el archivo README para el ejercicio 1 son correctas.
- En el proyecto eliminar todo el código de la resolución de los ejercicio y comenzar un proyecto base.
- Probar con al menos 2 soluciones distintas si el proyecto funciona.
- Elaborar un reporte con los detalles que surjan

**Comment by glabrat** [comment]
Ahora es que lo veo, no es muy diferente de lo comentado, tendré más noticias contigo.

Escrito desde linux, al fin.

**Comment by glabrat** [comment]
https://travis-ci.org/glabrat/bln-frontend-project1/builds/395524013
